## Ejercicio 3: Agente de inspección de calidad

### Ficha PEAS

| Elemento | Descripción |
|---|---|
| **Percepción (S)** | Matriz de inspección de 5×5, donde cada posición representa un elemento inspeccionado: 0 indica estado normal y 1 indica defecto. |
| **Acciones (A)** | Aprobar el lote, enviar a revisión manual o rechazar el lote. |
| **Entorno (E)** | Proceso de control de calidad, lote de productos y sistema de inspección. |
| **Objetivo** | Determinar el estado del lote a partir de la cantidad de defectos detectados durante la inspección. |
| **Medida de desempeño (P)** | Clasificar correctamente los lotes según la cantidad de defectos, evitando aprobar lotes con un número elevado de elementos defectuosos. |

### Justificación de las reglas

Para esta simulación se utiliza la cantidad total de defectos detectados en la matriz de inspección. Un lote con 0 defectos se aprueba directamente; si presenta entre 1 y 3 defectos se envía a revisión manual; y si presenta más de 3 defectos se rechaza. Estas reglas permiten diferenciar los lotes sin defectos, los que requieren una evaluación adicional y aquellos que presentan una cantidad mayor de defectos.

### Código

In [1]:
import numpy as np

def agente_inspeccion(matriz):
    # Validar que la matriz sea de 5x5
    if matriz.shape != (5, 5):
        return "error", "la matriz de inspección debe tener dimensiones 5x5"

    # Validar que la matriz contenga solamente 0 y 1
    if not np.all(np.isin(matriz, [0, 1])):
        return "error", "la matriz solo debe contener valores 0 y 1"

    # Contar la cantidad total de defectos
    cantidad_defectos = np.sum(matriz)

    # Tomar una decisión según la cantidad de defectos
    if cantidad_defectos == 0:
        return "aprobar", "el lote no presenta defectos"

    elif cantidad_defectos <= 3:
        return "revisión manual", f"el lote presenta {cantidad_defectos} defecto(s)"

    else:
        return "rechazar", f"el lote presenta {cantidad_defectos} defectos, superando el límite permitido"

### Simulación y pruebas

Se evalúa el agente utilizando diferentes matrices de inspección de 5×5. Las pruebas incluyen un lote sin defectos, lotes con cantidades intermedias de defectos, un caso límite de 3 defectos y un lote que supera dicho límite.

In [2]:
# Caso 1: 0 defectos
matriz_1 = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

# Caso 2: 1 defecto
matriz_2 = np.array([
    [1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

# Caso 3: 3 defectos - caso límite
matriz_3 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

# Caso 4: 4 defectos - supera el límite
matriz_4 = np.array([
    [1, 0, 0, 0, 1],
    [0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

matrices_prueba = [matriz_1, matriz_2, matriz_3, matriz_4]

for numero, matriz in enumerate(matrices_prueba, start=1):
    accion, motivo = agente_inspeccion(matriz)
    cantidad_defectos = np.sum(matriz)

    print(f"Caso {numero}")
    print(matriz)
    print(f"Cantidad de defectos: {cantidad_defectos}")
    print(f"Decisión: {accion}")
    print(f"Motivo: {motivo}")
    print("-" * 50)

Caso 1
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Cantidad de defectos: 0
Decisión: aprobar
Motivo: el lote no presenta defectos
--------------------------------------------------
Caso 2
[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Cantidad de defectos: 1
Decisión: revisión manual
Motivo: el lote presenta 1 defecto(s)
--------------------------------------------------
Caso 3
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Cantidad de defectos: 3
Decisión: revisión manual
Motivo: el lote presenta 3 defecto(s)
--------------------------------------------------
Caso 4
[[1 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Cantidad de defectos: 4
Decisión: rechazar
Motivo: el lote presenta 4 defectos, superando el límite permitido
--------------------------------------------------


### Visualización

Se representa gráficamente una matriz de inspección para facilitar la identificación de las posiciones normales y defectuosas del lote. La visualización complementa la decisión generada por el agente.